import os

import pytest

from vcd import Options


def test_filename_pattern():
    pat = Options.FILENAME_PATTERN

    def p(x):
        return pat.search(x).group(1)

    assert p('filename="GuAa docente de la asignatura.pdf"') == 'GuAa docente de la asignatura.pdf'
    assert p('filename="C02-Plan de Trabajo DAD-1819.pdf"') == 'C02-Plan de Trabajo DAD-1819.pdf'
    assert p('filename="B04-Practica 8-Mensajeria1819.pdf"') == 'B04-Practica 8-Mensajeria1819.pdf'
    assert p('filename="examenes.zip"') == 'examenes.zip'
    assert p('filename="A02-PresentacionDAD1819-Jaime.pdf"') == 'A02-PresentacionDAD1819-Jaime.pdf'
    assert p('filename="LVM-HOWTO.pdf"') == 'LVM-HOWTO.pdf'
    assert p('filename="agrst_t2.pdf"') == 'agrst_t2.pdf'
    assert p('filename="plan_de_trabajo_AGRST.pdf"') == 'plan_de_trabajo_AGRST.pdf'
    assert p('filename="agrst_t5.pdf"') == 'agrst_t5.pdf'
    assert p('filename="agrst_t6.pdf"') == 'agrst_t6.pdf'
    assert p('filename="agrst_presentacion.pdf"') == 'agrst_presentacion.pdf'
    assert p('filename="agrst_t7.pdf"') == 'agrst_t7.pdf'
    assert p('filename="agrst_t1.pdf"') == 'agrst_t1.pdf'
    assert p('filename="firmware-ralink_0.43_all.deb"') == 'firmware-ralink_0.43_all.deb'
    assert p('filename="GUAA ECO GRUPO 2 2018-2019.pdf"') == 'GUAA ECO GRUPO 2 2018-2019.pdf'
    assert p('filename="FOSDEM_2018_Closing_Keynote.pdf"') == 'FOSDEM_2018_Closing_Keynote.pdf'
    assert p('filename="agrst_t4.pdf"') == 'agrst_t4.pdf'
    assert p('filename="TESTCN ECO 12.xlsx"') == 'TESTCN ECO 12.xlsx'
    assert p('filename="EXAMEN CO 2018.pdf"') == 'EXAMEN CO 2018.pdf'
    assert p('filename="Chen_RAID_oficial.pdf"') == 'Chen_RAID_oficial.pdf'
    assert p('filename="TESTCN ADE14 DEF.xlsx"') == 'TESTCN ADE14 DEF.xlsx'
    assert p('filename="GUAA ADE GRUPO 4 2018-2019.pdf"') == 'GUAA ADE GRUPO 4 2018-2019.pdf'
    assert p('filename="TEST BALANZA ADE14.xlsx"') == 'TEST BALANZA ADE14.xlsx'
    assert p('filename="agrst_t8.pdf"') == 'agrst_t8.pdf'
    assert p('filename="TEST SOSTENIB ECO 12.xlsx"') == 'TEST SOSTENIB ECO 12.xlsx'
    assert p('filename="TEST SOSTENIB ADE14.xlsx"') == 'TEST SOSTENIB ADE14.xlsx'
    assert p('filename="infographic_debian.pdf"') == 'infographic_debian.pdf'
    assert p('filename="Tema 1-Ejercicios.pdf"') == 'Tema 1-Ejercicios.pdf'
    assert p('filename="Como Funciona La Nube v2.2.pdf"') == 'Como Funciona La Nube v2.2.pdf'
    assert p('filename="B03 Practica 1 SOLO ENUNCIADO.pdf"') == 'B03 Practica 1 SOLO ENUNCIADO.pdf'
    assert p('filename="CADENAS DE VALOR AAADIDO RED2.pdf"') == 'CADENAS DE VALOR AAADIDO RED2.pdf'
    assert p('filename="ESQUEMA TEMA 1 2019.docx"') == 'ESQUEMA TEMA 1 2019.docx'
    assert p('filename="TEST BALANZA ECO 12.xlsx"') == 'TEST BALANZA ECO 12.xlsx'
    assert p('filename="Tema 4-Paradigmas.pdf"') == 'Tema 4-Paradigmas.pdf'
    assert p('filename="ESQUEMA ENFOQUES.pdf"') == 'ESQUEMA ENFOQUES.pdf'
    assert p('filename="ORGANIGRAMA DE LA ONU.pdf"') == 'ORGANIGRAMA DE LA ONU.pdf'
    assert p('filename="EJEMPLOS PREGUNTAS EXAMEN.pdf"') == 'EJEMPLOS PREGUNTAS EXAMEN.pdf'
    assert p('filename="REPLANTEARSE EL PIB.pdf"') == 'REPLANTEARSE EL PIB.pdf'
    assert p('filename="B06-Practica 9-Chat 1819.pdf"') == 'B06-Practica 9-Chat 1819.pdf'
    assert p('filename="GuAa acceso a las cuentas.pdf"') == 'GuAa acceso a las cuentas.pdf'
    assert p('filename="TEMA 3 2019.docx"') == 'TEMA 3 2019.docx'
    assert p('filename="CONTABILIDAD NACIONAL.pdf"') == 'CONTABILIDAD NACIONAL.pdf'
    assert p('filename="Test CN y PIB 2019 SC.xlsx"') == 'Test CN y PIB 2019 SC.xlsx'
    assert p('filename="GuiaDocente_AGRST_1819.pdf"') == 'GuiaDocente_AGRST_1819.pdf'
    assert p('filename="ANA 2016.xlsx"') == 'ANA 2016.xlsx'
    assert p('filename="Tema 4 2019.docx"') == 'Tema 4 2019.docx'
    assert p('filename="Conceptos y preguntas. Tema 3.pdf"') == 'Conceptos y preguntas. Tema 3.pdf'
    assert p('filename="HE Y CB.xlsx"') == 'HE Y CB.xlsx'
    assert p('filename="VADEOS SOSTENIBILIDAD.pdf"') == 'VADEOS SOSTENIBILIDAD.pdf'
    assert p('filename="Practica 14-Hash.pdf"') == 'Practica 14-Hash.pdf'
    assert p('filename="TESTIDH ECO 12.xlsx"') == 'TESTIDH ECO 12.xlsx'
    assert p('filename="MEDIDAS DE SOSTENIBILIDAD.pdf"') == 'MEDIDAS DE SOSTENIBILIDAD.pdf'
    assert p('filename="NOTAS TACNICAS HDR2018.pdf"') == 'NOTAS TACNICAS HDR2018.pdf'
    assert p('filename="Conceptos y preguntas TEMA 5.pdf"') == 'Conceptos y preguntas TEMA 5.pdf'
    assert p('filename="VisiA3n contabilidad nacional.pdf"') == 'VisiA3n contabilidad nacional.pdf'
    assert p('filename="Conceptos y preguntas. Tema 6.pdf"') == 'Conceptos y preguntas. Tema 6.pdf'
    assert p('filename="Conceptos y preguntas. Tema 4.pdf"') == 'Conceptos y preguntas. Tema 4.pdf'
    assert p('filename="MATERIAL DESARROLLO HUMANO.pdf"') == 'MATERIAL DESARROLLO HUMANO.pdf'
    assert p('filename="Conceptos y preguntas. Tema 7.pdf"') == 'Conceptos y preguntas. Tema 7.pdf'
    assert p('filename="Conceptos y preguntas. Tema 8.pdf"') == 'Conceptos y preguntas. Tema 8.pdf'
    assert p('filename="CPD SOSTENIBILIDAD 2.docx"') == 'CPD SOSTENIBILIDAD 2.docx'
    assert p('filename="Tema 2-IPC.pdf"') == 'Tema 2-IPC.pdf'
    assert p('filename="ESQUEMA DEL TEMA 7.docx"') == 'ESQUEMA DEL TEMA 7.docx'
    assert p('filename="EJERCICIOS TEMA 2.pdf"') == 'EJERCICIOS TEMA 2.pdf'
    assert p('filename="TRANSFERENCIA Y TASA GOOGLE.pdf"') == 'TRANSFERENCIA Y TASA GOOGLE.pdf'
    assert p('filename="BALANZA DE PAGOS.pdf"') == 'BALANZA DE PAGOS.pdf'
    assert p('filename="Tema 8 2019.docx"') == 'Tema 8 2019.docx'
    assert p('filename="Tema 5-Nombres.pdf"') == 'Tema 5-Nombres.pdf'
    assert p('filename="B05-Practica 5-Buscaminas.pdf"') == 'B05-Practica 5-Buscaminas.pdf'
    assert p('filename="Tema 3-El API de Sockets Java.pdf"') == 'Tema 3-El API de Sockets Java.pdf'
    assert p('filename="70 ANIVERSARIO DEL GATT.pdf"') == '70 ANIVERSARIO DEL GATT.pdf'
    assert p('filename="BALANZA DE PAGOS-2019.pdf"') == 'BALANZA DE PAGOS-2019.pdf'
    assert p('filename="ESQUEMA TEMA 9 2019 RED.docx"') == 'ESQUEMA TEMA 9 2019 RED.docx'
    assert p('filename="Timers.rar"') == 'Timers.rar'
    assert p('filename="agrst_t3.pdf"') == 'agrst_t3.pdf'
    assert p('filename="WEO ABRIL2019.pdf"') == 'WEO ABRIL2019.pdf'
    assert p('filename="Teclado.rar"') == 'Teclado.rar'
    assert p('filename="B08 PISTAS Y ENUNCIADO.pdf"') == 'B08 PISTAS Y ENUNCIADO.pdf'
    assert p('filename="auxiliar.tar.gz"') == 'auxiliar.tar.gz'
    assert p('filename="OXFAM GUERRAS FISCALES.pdf"') == 'OXFAM GUERRAS FISCALES.pdf'
    assert p('filename="TEMA 5 2019.docx"') == 'TEMA 5 2019.docx'
    assert p('filename="GuiaDocente_DCDC_1819.pdf"') == 'GuiaDocente_DCDC_1819.pdf'
    assert p('filename="B05-Practica 12.pdf"') == 'B05-Practica 12.pdf'
    assert p('filename="B06-Practica 6-.pdf"') == 'B06-Practica 6-.pdf'
    assert p('filename="DesmaterializaciA3n.pdf"') == 'DesmaterializaciA3n.pdf'
    assert p('filename="P2.pdf"') == 'P2.pdf'
    assert p('filename="P3.rar"') == 'P3.rar'
    assert p('filename="RESUMEN  TEMA 2 2019.docx"') == 'RESUMEN  TEMA 2 2019.docx'
    assert p('filename="dsPIC33FJ32GP204.pdf"') == 'dsPIC33FJ32GP204.pdf'
    assert p('filename="Practica 2.pdf"') == 'Practica 2.pdf'
    assert p('filename="P4.pdf"') == 'P4.pdf'
    assert p('filename="iprt1718_tema0_laboratorio.pdf"') == 'iprt1718_tema0_laboratorio.pdf'
    assert p('filename="Servicios Web RESTful en Java.pdf"') == 'Servicios Web RESTful en Java.pdf'
    assert p('filename="Tema 6 - Sincronizacion.pdf"') == 'Tema 6 - Sincronizacion.pdf'
    assert p('filename="DSP Library Documentation.rar"') == 'DSP Library Documentation.rar'
    assert p('filename="KATE RAWORTH Y EL DONUT.pdf"') == 'KATE RAWORTH Y EL DONUT.pdf'
    assert p('filename="P0.rar"') == 'P0.rar'
    assert p('filename="BIBLIOGRAFAA DE APOYO.pdf"') == 'BIBLIOGRAFAA DE APOYO.pdf'
    assert p('filename="TEMA 6 2019.docx"') == 'TEMA 6 2019.docx'
    assert p('filename="iprt1819_plantilla.docx"') == 'iprt1819_plantilla.docx'
    assert p('filename="iprt1718_examen_ordinario.pdf"') == 'iprt1718_examen_ordinario.pdf'
    assert p('filename="hoja_1.pdf"') == 'hoja_1.pdf'
    assert p('filename="hoja_2.pdf"') == 'hoja_2.pdf'
    assert p('filename="iprt1819_tema5_problemas.pdf"') == 'iprt1819_tema5_problemas.pdf'
    assert p('filename="B02-Practica 15-JAX-RS.pdf"') == 'B02-Practica 15-JAX-RS.pdf'
    assert p('filename="Transparencias_DCDC_DSPs.pdf"') == 'Transparencias_DCDC_DSPs.pdf'
    assert p('filename="iprt1819_tema3_guia.pdf"') == 'iprt1819_tema3_guia.pdf'
    assert p('filename="iprt1819_tema5_guia.pdf"') == 'iprt1819_tema5_guia.pdf'
    assert p('filename="CINE Y CRISIS.pdf"') == 'CINE Y CRISIS.pdf'
    assert p('filename="P1.pdf"') == 'P1.pdf'
    assert p('filename="ELINOR OLSTROM.pdf"') == 'ELINOR OLSTROM.pdf'
    assert p('filename="Tema 8 - Tolerancia a fallos.pdf"') == 'Tema 8 - Tolerancia a fallos.pdf'
    assert p('filename="ftr04_imprimir.pdf"') == 'ftr04_imprimir.pdf'
    assert p('filename="dsPIC33FJ32GP304.pdf"') == 'dsPIC33FJ32GP304.pdf'
    assert p('filename="iprt1819_tema0_presentacion.pdf"') == 'iprt1819_tema0_presentacion.pdf'
    assert p('filename="eval_agrst003.txt"') == 'eval_agrst003.txt'
    assert p('filename="practica1.pdf"') == 'practica1.pdf'
    assert p('filename="memoria2_agrst003.pdf"') == 'memoria2_agrst003.pdf'
    assert p('filename="P2.rar"') == 'P2.rar'
    assert p('filename="practica3.pdf"') == 'practica3.pdf'
    assert p('filename="ftr05.pdf"') == 'ftr05.pdf'
    assert p('filename="informe1-agrst003.pdf"') == 'informe1-agrst003.pdf'
    assert p('filename="P4.rar"') == 'P4.rar'
    assert p('filename="plantilla1.doc"') == 'plantilla1.doc'
    assert p('filename="MPLAB_XC16_Asm_Link.pdf"') == 'MPLAB_XC16_Asm_Link.pdf'
    assert p('filename="B07-Practica 7-Servidor.pdf"') == 'B07-Practica 7-Servidor.pdf'
    assert p('filename="memoria3_agrst003.pdf"') == 'memoria3_agrst003.pdf'
    assert p('filename="plantilla2.doc"') == 'plantilla2.doc'
    assert p('filename="plantilla3.doc"') == 'plantilla3.doc'
    assert p('filename="iprt1819_tema4_guia.pdf"') == 'iprt1819_tema4_guia.pdf'
    assert p('filename="eval_agrst003.txt"') == 'eval_agrst003.txt'
    assert p('filename="Proyecto voluntario.pdf"') == 'Proyecto voluntario.pdf'
    assert p('filename="P1.rar"') == 'P1.rar'
    assert p('filename="plantilla4.doc"') == 'plantilla4.doc'
    assert p('filename="meltdown.pdf"') == 'meltdown.pdf'
    assert p('filename="spectre.pdf"') == 'spectre.pdf'
    assert p('filename="plantilla5.doc"') == 'plantilla5.doc'
    assert p('filename="P0.pdf"') == 'P0.pdf'
    assert p('filename="eval_agrst003.txt"') == 'eval_agrst003.txt'
    assert p('filename="ftr05_imprimir.pdf"') == 'ftr05_imprimir.pdf'
    assert p('filename="ftr03.pdf"') == 'ftr03.pdf'
    assert p('filename="practica5.pdf"') == 'practica5.pdf'
    assert p('filename="ftr01_imprimir.pdf"') == 'ftr01_imprimir.pdf'
    assert p('filename="plan_de_trabajo_SCG_1819.pdf"') == 'plan_de_trabajo_SCG_1819.pdf'
    assert p('filename="ftr01.pdf"') == 'ftr01.pdf'
    assert p('filename="iprt1819_tema1_teoria.pdf"') == 'iprt1819_tema1_teoria.pdf'
    assert p('filename="iprt1819_tema3_problemas.pdf"') == 'iprt1819_tema3_problemas.pdf'
    assert p('filename="GuiaDocente_SCG_1819.pdf"') == 'GuiaDocente_SCG_1819.pdf'
    assert p('filename="Proteus Tutorials.pdf"') == 'Proteus Tutorials.pdf'
    assert p('filename="ACTUALIZACIAN HDR2018.pdf"') == 'ACTUALIZACIAN HDR2018.pdf'
    assert p('filename="p5.pdf"') == 'p5.pdf'
    assert p('filename="memoria4_agrst003.pdf"') == 'memoria4_agrst003.pdf'
    assert p('filename="eval_agrst003.txt"') == 'eval_agrst003.txt'
    assert p('filename="ficheros_web.tar.gz"') == 'ficheros_web.tar.gz'
    assert p('filename="SCG_ecuaciones_a_memorizar.pdf"') == 'SCG_ecuaciones_a_memorizar.pdf'
    assert p('filename="epn_about_the_2009.pdf"') == 'epn_about_the_2009.pdf'
    assert p('filename="ftr02_imprimir.pdf"') == 'ftr02_imprimir.pdf'
    assert p('filename="scg_tema1.pdf"') == 'scg_tema1.pdf'
    assert p('filename="iprt1819_tema4.pdf"') == 'iprt1819_tema4.pdf'
    assert p('filename="practica2.pdf"') == 'practica2.pdf'
    assert p('filename="TESTIDH ADE14.xlsx"') == 'TESTIDH ADE14.xlsx'
    assert p('filename="scg_tema3_ejercicios.pdf"') == 'scg_tema3_ejercicios.pdf'
    assert p('filename="practica4.pdf"') == 'practica4.pdf'
    assert p('filename="ftr03_imprimir.pdf"') == 'ftr03_imprimir.pdf'
    assert p('filename="scg_tema3_complementos.pdf"') == 'scg_tema3_complementos.pdf'
    assert p('filename="kao-lecture-slides.pdf"') == 'kao-lecture-slides.pdf'
    assert p('filename="scg_ejercicios_tema1y2.pdf"') == 'scg_ejercicios_tema1y2.pdf'
    assert p('filename="ftr04.pdf"') == 'ftr04.pdf'
    assert p('filename="kao-lecture.pdf"') == 'kao-lecture.pdf'
    assert p('filename="articulo_Kao_Hockhman_1966.pdf"') == 'articulo_Kao_Hockhman_1966.pdf'
    assert p('filename="iprt1819_gruposlaboratorio.pdf"') == 'iprt1819_gruposlaboratorio.pdf'
    assert p('filename="SCG_Tema_6_primera_parte_1617.pdf"') == 'SCG_Tema_6_primera_parte_1617.pdf'
    assert p('filename="Quiz_scgtemas1a3.pdf"') == 'Quiz_scgtemas1a3.pdf'
    assert p('filename="ftr02.pdf"') == 'ftr02.pdf'
    assert p('filename="NotasTestLaboratorioS1.pdf"') == 'NotasTestLaboratorioS1.pdf'
    assert p('filename="scg_tema3.pdf"') == 'scg_tema3.pdf'
    assert p('filename="NotasSeminarioTema1.pdf"') == 'NotasSeminarioTema1.pdf'
    assert p('filename="NotasSeminarioTema2.pdf"') == 'NotasSeminarioTema2.pdf'
    assert p('filename="iprt1819_tema2_teoria.pdf"') == 'iprt1819_tema2_teoria.pdf'
    assert p('filename="NotasSeminarioTema3.pdf"') == 'NotasSeminarioTema3.pdf'
    assert p('filename="iprt1819_tema2_guia.pdf"') == 'iprt1819_tema2_guia.pdf'
    assert p('filename="scg_introduccion1819.pdf"') == 'scg_introduccion1819.pdf'
    assert p('filename="SCG_Ejercicios_T4-5 2018_19.pdf"') == 'SCG_Ejercicios_T4-5 2018_19.pdf'
    assert p('filename="NotasSeminarioTema4.pdf"') == 'NotasSeminarioTema4.pdf'
    assert p('filename="scg_tema2.pdf"') == 'scg_tema2.pdf'
    assert p('filename="Practica4_TC_18-19_V1.pdf"') == 'Practica4_TC_18-19_V1.pdf'
    assert p('filename="iprt1819_tema2_problemas.pdf"') == 'iprt1819_tema2_problemas.pdf'
    assert p('filename="Practica5_TC_18-19.pdf"') == 'Practica5_TC_18-19.pdf'
    assert p('filename="Grupos de laboratorio.pdf"') == 'Grupos de laboratorio.pdf'
    assert p('filename="NotasSeminarioTema4"') == 'NotasSeminarioTema4'
    assert p('filename="torre_arganda.pdf"') == 'torre_arganda.pdf'
    assert p('filename="co_hojas_especificaciones.zip"') == 'co_hojas_especificaciones.zip'
    assert p('filename="NotasTestLaboratorioS2.pdf"') == 'NotasTestLaboratorioS2.pdf'
    assert p('filename="NotasTestLaboratorioS3.pdf"') == 'NotasTestLaboratorioS3.pdf'
    assert p('filename="Seminario_T4_TC_18-19.pdf"') == 'Seminario_T4_TC_18-19.pdf'
    assert p('filename="GuiaDocente_TDS_1819.pdf"') == 'GuiaDocente_TDS_1819.pdf'
    assert p('filename="NotasTestLaboratorioS5.pdf"') == 'NotasTestLaboratorioS5.pdf'
    assert p('filename="SCG_Entrega_Componentes_1819.pdf"') == 'SCG_Entrega_Componentes_1819.pdf'
    assert p('filename="NotasTestLaboratorioS4.pdf"') == 'NotasTestLaboratorioS4.pdf'
    assert p('filename="Practica8_TC_T5_1_2018-2019.pdf"') == 'Practica8_TC_T5_1_2018-2019.pdf'
    assert p('filename="grupo de tarde.7z"') == 'grupo de tarde.7z'
    assert p('filename="Transparencias TDS_T01.pdf"') == 'Transparencias TDS_T01.pdf'
    assert p('filename="iprt1819_tema4_problemas.pdf"') == 'iprt1819_tema4_problemas.pdf'
    assert p('filename="Seminario_T3_TC_18-19.pdf"') == 'Seminario_T3_TC_18-19.pdf'
    assert p('filename="Grupo de maA+-ana.7z"') == 'Grupo de maA+-ana.7z'
    assert p('filename="NotasTestLaboratorioS6.pdf"') == 'NotasTestLaboratorioS6.pdf'
    assert p('filename="P3.pdf"') == 'P3.pdf'
    assert p('filename="NotasTestLaboratorioS8.pdf"') == 'NotasTestLaboratorioS8.pdf'
    assert p('filename="iprt1819_tema3_teoria.pdf"') == 'iprt1819_tema3_teoria.pdf'
    assert p('filename="Practica6_T4_2_TC_18-19.pdf"') == 'Practica6_T4_2_TC_18-19.pdf'
    assert p('filename="P5_PAM_demo.m"') == 'P5_PAM_demo.m'
    assert p('filename="Capturas de pantalla.pdf"') == 'Capturas de pantalla.pdf'
    assert p('filename="Transparencias_T03_TDS.pdf"') == 'Transparencias_T03_TDS.pdf'
    assert p('filename="turnos_iniciales_2019.pdf"') == 'turnos_iniciales_2019.pdf'
    assert p('filename="P1_TDS_2018.pdf"') == 'P1_TDS_2018.pdf'
    assert p('filename="TDS_Seminario2_2018.pdf"') == 'TDS_Seminario2_2018.pdf'
    assert p('filename="Plantilla_evaluacion_P1.docx"') == 'Plantilla_evaluacion_P1.docx'
    assert p('filename="Generador.vi"') == 'Generador.vi'
    assert p('filename="NotasTestLaboratorioS7.pdf"') == 'NotasTestLaboratorioS7.pdf'
    assert p('filename="Plan de Trabajo_TDS_2019.pdf"') == 'Plan de Trabajo_TDS_2019.pdf'
    assert p('filename="P6_PCM_cuantif.m"') == 'P6_PCM_cuantif.m'
    assert p('filename="lab-T5-P8_ISI.zip"') == 'lab-T5-P8_ISI.zip'
    assert p('filename="Instrucciones de envio.pdf"') == 'Instrucciones de envio.pdf'
    assert p('filename="iprt1819_tema5.pdf"') == 'iprt1819_tema5.pdf'
    assert p('filename="Evaluacion Objetivos docentes.pdf"') == 'Evaluacion Objetivos docentes.pdf'
    assert p('filename="p2_TDS_2019.pdf"') == 'p2_TDS_2019.pdf'
    assert p('filename="Calificaciones_P2.pdf"') == 'Calificaciones_P2.pdf'
    assert p('filename="T02_Respuesta en frecuencia.pdf"') == 'T02_Respuesta en frecuencia.pdf'
    assert p('filename="FiltrosP4_2016.zip"') == 'FiltrosP4_2016.zip'
    assert p('filename="kaisser.vi"') == 'kaisser.vi'
    assert p('filename="iprt1819_planificacioIn180907.pdf"') == 'iprt1819_planificacioIn180907.pdf'
    assert p('filename="turnos_2_2019.pdf"') == 'turnos_2_2019.pdf'
    assert p('filename="Instalacion de labview 2019.pdf"') == 'Instalacion de labview 2019.pdf'
    assert p('filename="imagenes P9.zip"') == 'imagenes P9.zip'
    assert p('filename="pract2_memorias_control_mem.pdf"') == 'pract2_memorias_control_mem.pdf'
    assert p('filename="Diezmado e interpolacion_2016.pdf"') == 'Diezmado e interpolacion_2016.pdf'
    assert p('filename="EstimaciA3n espectral.pdf"') == 'EstimaciA3n espectral.pdf'
    assert p('filename="Seminario_T5_TC_18-19.pdf"') == 'Seminario_T5_TC_18-19.pdf'
    assert p('filename="Calificaciones_P1.pdf"') == 'Calificaciones_P1.pdf'
    assert p('filename="NotasSeminarioTema2.pdf"') == 'NotasSeminarioTema2.pdf'
    assert p('filename="lab-T5-P9_ModDig.zip"') == 'lab-T5-P9_ModDig.zip'
    assert p('filename="imagenes_P8.zip"') == 'imagenes_P8.zip'
    assert p('filename="P3_DFT_TDS_2019.pdf"') == 'P3_DFT_TDS_2019.pdf'
    assert p('filename="P9_maquina de estados_TDS.pdf"') == 'P9_maquina de estados_TDS.pdf'
    assert p('filename="pract2_memorias_control.pdf"') == 'pract2_memorias_control.pdf'
    assert p('filename="A24-RST guia_docente-1819.pdf"') == 'A24-RST guia_docente-1819.pdf'
    assert p('filename="A06 Presentacion Tema 2.pdf"') == 'A06 Presentacion Tema 2.pdf'
    assert p('filename="Ejemplo AD 2 canales.rar"') == 'Ejemplo AD 2 canales.rar'
    assert p('filename="Practica9_TC_T5_2_2018-2019.pdf"') == 'Practica9_TC_T5_2_2018-2019.pdf'
    assert p('filename="S2.A3_solucion.pdf"') == 'S2.A3_solucion.pdf'
    assert p('filename="pract3_UART_receiver.pdf"') == 'pract3_UART_receiver.pdf'
    assert p('filename="Tecnica de ventana.pdf"') == 'Tecnica de ventana.pdf'
    assert p('filename="Esquemas P8.7z"') == 'Esquemas P8.7z'
    assert p('filename="WDM_montajeTOTAL_AVI_VOZ_x264.mp4"') == 'WDM_montajeTOTAL_AVI_VOZ_x264.mp4'
    assert p('filename="10_1_final.vi"') == '10_1_final.vi'
    assert p('filename="cyclone4-overview.pdf"') == 'cyclone4-overview.pdf'
    assert p('filename="TDS_Seminario1_2016.pdf"') == 'TDS_Seminario1_2016.pdf'
    assert p('filename="telemando.zip"') == 'telemando.zip'
    assert p('filename="Pract4-tutorial_TimeQuest.pdf"') == 'Pract4-tutorial_TimeQuest.pdf'
    assert p('filename="introduccion_laboratorio.pdf"') == 'introduccion_laboratorio.pdf'
    assert p('filename="DE0_Nano.qsf"') == 'DE0_Nano.qsf'
    assert p('filename="quartus2_introduction.pdf"') == 'quartus2_introduction.pdf'
    assert p('filename="Practica3_TC_18-19.pdf"') == 'Practica3_TC_18-19.pdf'
    assert p('filename="Pract5-sdc_receptor_UART_FIFO.pdf"') == 'Pract5-sdc_receptor_UART_FIFO.pdf'
    assert p('filename="TX-RD_gen.mif"') == 'TX-RD_gen.mif'
    assert p('filename="IMAQ Readfile.vi"') == 'IMAQ Readfile.vi'
    assert p('filename="p5-Alloza_Herrezuelo-dcdc_p5.rar"') == 'p5-Alloza_Herrezuelo-dcdc_p5.rar'
    assert p('filename="p3-Alloza_Herrezuelo-dcdc_p3.rar"') == 'p3-Alloza_Herrezuelo-dcdc_p3.rar'
    assert p('filename="A03 Presentacion_RST_1819.pdf"') == 'A03 Presentacion_RST_1819.pdf'
    assert p('filename="shifter_latches.zip"') == 'shifter_latches.zip'
    assert p('filename="informe-p5.pdf"') == 'informe-p5.pdf'
    assert p('filename="iprtx11_P2.pdf"') == 'iprtx11_P2.pdf'
    assert p('filename="Prob1.pdf"') == 'Prob1.pdf'
    assert p('filename="TF-2D.pdf"') == 'TF-2D.pdf'
    assert p('filename="informe3_iprtx11.pdf"') == 'informe3_iprtx11.pdf'
    assert p('filename="Tema1.pdf"') == 'Tema1.pdf'
    assert p('filename="A06 Plan de trabajo-RST-1819.pdf"') == 'A06 Plan de trabajo-RST-1819.pdf'
    assert p('filename="P2_iprtx11.pdf"') == 'P2_iprtx11.pdf'
    assert p('filename="solucion_problema4.pdf"') == 'solucion_problema4.pdf'
    assert p('filename="ospf.cap"') == 'ospf.cap'
    assert p('filename="ripv2.cap"') == 'ripv2.cap'
    assert p('filename="informe2_iprtx11.pdf"') == 'informe2_iprtx11.pdf'
    assert p('filename="informe4_iprtx11.pdf"') == 'informe4_iprtx11.pdf'
    assert p('filename="manual_Netgear_GS108T.pdf"') == 'manual_Netgear_GS108T.pdf'
    assert p('filename="sol_prob11_tema1.jpg"') == 'sol_prob11_tema1.jpg'
    assert p('filename="iprtx11 P4.pdf"') == 'iprtx11 P4.pdf'
    assert p('filename="ejercicios scg.pdf"') == 'ejercicios scg.pdf'
    assert p('filename="Prob2.pdf"') == 'Prob2.pdf'
    assert p('filename="PlanificaciA3nSCG20182019.ppt"') == 'PlanificaciA3nSCG20182019.ppt'
    assert p('filename="scg_cables.pdf"') == 'scg_cables.pdf'
    assert p('filename="informe5_iprtx11.pdf"') == 'informe5_iprtx11.pdf'
    assert p('filename="02_Fibra_Corning_SMF-28.pdf"') == '02_Fibra_Corning_SMF-28.pdf'
    assert p('filename="Tema2.pdf"') == 'Tema2.pdf'
    assert p('filename="11_filtro_fabry_perot_jdsu.pdf"') == '11_filtro_fabry_perot_jdsu.pdf'
    assert p('filename="DE0_Nano_User_Manual.pdf"') == 'DE0_Nano_User_Manual.pdf'
    assert p('filename="03_Fibra_OFS_AllWave.pdf"') == '03_Fibra_OFS_AllWave.pdf'
    assert p('filename="p6-Alloza_Herrezuelo-dcdc_p6.rar"') == 'p6-Alloza_Herrezuelo-dcdc_p6.rar'
    assert p('filename="16_moduladorNRZ_jdsu.pdf"') == '16_moduladorNRZ_jdsu.pdf'
    assert p('filename="17_laser_fabryperot_optoway.pdf"') == '17_laser_fabryperot_optoway.pdf'
    assert p('filename="12_FBG_jdsu.pdf"') == '12_FBG_jdsu.pdf'
    assert p('filename="p2-entrega.zip"') == 'p2-entrega.zip'
    assert p('filename="wdm_efectos_nolineales.pdf"') == 'wdm_efectos_nolineales.pdf'
    assert p('filename="06_conectores.pdf"') == '06_conectores.pdf'
    assert p('filename="GuiaPractica2_SGC_Grado.pdf"') == 'GuiaPractica2_SGC_Grado.pdf'
    assert p('filename="22_APD_spectrolab.pdf"') == '22_APD_spectrolab.pdf'
    assert p('filename="shifter_latches_low_frequency.zip"') == 'shifter_latches_low_frequency.zip'
    assert p('filename="TC 2004-09 examen extraord.pdf"') == 'TC 2004-09 examen extraord.pdf'
    assert p('filename="19_laser_mod_directa_jdsu.pdf"') == '19_laser_mod_directa_jdsu.pdf'
    assert p('filename="05_Fibra_Corning_LEAF.pdf"') == '05_Fibra_Corning_LEAF.pdf'
    assert p('filename="24_receptor_ERM588_jdsu.pdf"') == '24_receptor_ERM588_jdsu.pdf'
    assert p('filename="15_conmutador_MEMS_jdsu.pdf"') == '15_conmutador_MEMS_jdsu.pdf'
    assert p('filename="13_AWG_jdsu.pdf"') == '13_AWG_jdsu.pdf'
    assert p('filename="10_circulador_jdsu.pdf"') == '10_circulador_jdsu.pdf'
    assert p('filename="23_receptor_pd78s3a_samsung.pdf"') == '23_receptor_pd78s3a_samsung.pdf'
    assert p('filename="TC 2010-06 junio ordinario.pdf"') == 'TC 2010-06 junio ordinario.pdf'
    assert p('filename="14_EDFA_C_hasta32canales_jdsu.pdf"') == '14_EDFA_C_hasta32canales_jdsu.pdf'
    assert p('filename="apuntarseSCG_2018.docx"') == 'apuntarseSCG_2018.docx'
    assert p('filename="TC 2004-09 soluciA3n.pdf"') == 'TC 2004-09 soluciA3n.pdf'
    assert p('filename="informe5_iprtx11.pdf"') == 'informe5_iprtx11.pdf'
    assert p('filename="TC 2004-06 junio examen ord.pdf"') == 'TC 2004-06 junio examen ord.pdf'
    assert p('filename="TC 2011-05 mayo ordinario.pdf"') == 'TC 2011-05 mayo ordinario.pdf'
    assert p('filename="21_pin_MF432_zarlink.pdf"') == '21_pin_MF432_zarlink.pdf'
    assert p('filename="TC 2008-06 junio ordinario.pdf"') == 'TC 2008-06 junio ordinario.pdf'
    assert p('filename="07_Cable_OFS_ACCUMAX.pdf"') == '07_Cable_OFS_ACCUMAX.pdf'
    assert p('filename="TC 2012-06 junio ordinario.pdf"') == 'TC 2012-06 junio ordinario.pdf'
    assert p('filename="20_led_MF431_zarlink.pdf"') == '20_led_MF431_zarlink.pdf'
    assert p('filename="Nick_Cartoon_conectores.jpg"') == 'Nick_Cartoon_conectores.jpg'
    assert p('filename="TC 2012-01 examen ordinario.pdf"') == 'TC 2012-01 examen ordinario.pdf'
    assert p('filename="Cables_Zettabyte_Era.pdf"') == 'Cables_Zettabyte_Era.pdf'
    assert p('filename="TC 2009-06 junio ordinario.pdf"') == 'TC 2009-06 junio ordinario.pdf'
    assert p('filename="ManualOTDR_Monomodo.pdf"') == 'ManualOTDR_Monomodo.pdf'
    assert p('filename="Problemas_Tema1.pdf"') == 'Problemas_Tema1.pdf'
    assert p('filename="Cuestiones_Tema1.pdf"') == 'Cuestiones_Tema1.pdf'
    assert p('filename="Cuestiones_Tema2.pdf"') == 'Cuestiones_Tema2.pdf'
    assert p('filename="scg_automocion.pdf"') == 'scg_automocion.pdf'
    assert p('filename="Soluciones_Problemas_Tema1.pdf"') == 'Soluciones_Problemas_Tema1.pdf'
    assert p('filename="p5_DiseA+-oFiltros_ TDS_2019.pdf"') == 'p5_DiseA+-oFiltros_ TDS_2019.pdf'
    assert p('filename="Cuestiones_Tema3.pdf"') == 'Cuestiones_Tema3.pdf'
    assert p('filename="09_acoplador_soldado_jdsu.pdf"') == '09_acoplador_soldado_jdsu.pdf'
    assert p('filename="Practica2_TC_18-19.pdf"') == 'Practica2_TC_18-19.pdf'
    assert p('filename="GuiaPractica4_SGC_Grado.pdf"') == 'GuiaPractica4_SGC_Grado.pdf'
    assert p('filename="Tutorial_TC_18-19.pdf"') == 'Tutorial_TC_18-19.pdf'
    assert p('filename="ProblemasResueltos_Tema2.pdf"') == 'ProblemasResueltos_Tema2.pdf'
    assert p('filename="ProblemasResueltos_Tema3.pdf"') == 'ProblemasResueltos_Tema3.pdf'
    assert p('filename="Practica5_SCG.pdf"') == 'Practica5_SCG.pdf'
    assert p('filename="GuiaPractica3_SGC_grado.pdf"') == 'GuiaPractica3_SGC_grado.pdf'
    assert p('filename="Soluciones_Problemas_Tema2.pdf"') == 'Soluciones_Problemas_Tema2.pdf'
    assert p('filename="Seminario_Tema2_TC_18-19.pdf"') == 'Seminario_Tema2_TC_18-19.pdf'
    assert p('filename="signal.mat"') == 'signal.mat'
    assert p('filename="scg_redes_HFC.pdf"') == 'scg_redes_HFC.pdf'
    assert p('filename="Problemas_Tema2.pdf"') == 'Problemas_Tema2.pdf'
    assert p('filename="ManualOTDR_Multimodo.pdf"') == 'ManualOTDR_Multimodo.pdf'
    assert p('filename="Problemas_Tema5.pdf"') == 'Problemas_Tema5.pdf'
    assert p('filename="Cuestiones_Tema4.pdf"') == 'Cuestiones_Tema4.pdf'
    assert p('filename="TDS_LABVIEW-Jun16_grupo1.pdf"') == 'TDS_LABVIEW-Jun16_grupo1.pdf'
    assert p('filename="GuiaPractica6_SGC_GradoNUEVA.pdf"') == 'GuiaPractica6_SGC_GradoNUEVA.pdf'
    assert p('filename="TC_GuiaDocente_curso2018-19.pdf"') == 'TC_GuiaDocente_curso2018-19.pdf'
    assert p('filename="Ejercicio6-tema3-SCG.pdf"') == 'Ejercicio6-tema3-SCG.pdf'
    assert p('filename="TDS_LABVIEW-Jul16.pdf"') == 'TDS_LABVIEW-Jul16.pdf'
    assert p('filename="Soluciones_Problemas_Tema5.pdf"') == 'Soluciones_Problemas_Tema5.pdf'
    assert p('filename="Cuestiones_Tema5.pdf"') == 'Cuestiones_Tema5.pdf'
    assert p('filename="ProblemasResueltos_Tema4.pdf"') == 'ProblemasResueltos_Tema4.pdf'
    assert p('filename="TDS_Teoria jun_2016.pdf"') == 'TDS_Teoria jun_2016.pdf'
    assert p('filename="gray2bin.m"') == 'gray2bin.m'
    assert p('filename="P6_PCM_cuantif.m"') == 'P6_PCM_cuantif.m'
    assert p('filename="Practica1_TC_18-19.pdf"') == 'Practica1_TC_18-19.pdf'
    assert p('filename="Anexo1_TC_2018-2019.pdf"') == 'Anexo1_TC_2018-2019.pdf'
    assert p('filename="Problemas_Tema4.pdf"') == 'Problemas_Tema4.pdf'
    assert p('filename="Documento 2.pdf"') == 'Documento 2.pdf'
    assert p('filename="Problemas_Tema3.pdf"') == 'Problemas_Tema3.pdf'
    assert p('filename="TDS-LabVIEW-2017-grupo2.pdf"') == 'TDS-LabVIEW-2017-grupo2.pdf'
    assert p('filename="ReadAD2.vi"') == 'ReadAD2.vi'
    assert p('filename="bin2gray.m"') == 'bin2gray.m'
    assert p('filename="P7_PCM_codif_decodif.m"') == 'P7_PCM_codif_decodif.m'
    assert p('filename="TeoriaPractica4_SGC_Grado.pdf"') == 'TeoriaPractica4_SGC_Grado.pdf'
    assert p('filename="TDS_LABVIEW-Jun16_grupo2.pdf"') == 'TDS_LABVIEW-Jun16_grupo2.pdf'
    assert p('filename="TeoriaPractica2_SGC_Grado.pdf"') == 'TeoriaPractica2_SGC_Grado.pdf'
    assert p('filename="informe-9.pdf"') == 'informe-9.pdf'
    assert p('filename="Seminario_Tema1_TC_18-19.pdf"') == 'Seminario_Tema1_TC_18-19.pdf'
    assert p('filename="FinADDA2.vi"') == 'FinADDA2.vi'
    assert p('filename="TDS-LabVIEW-2017-grupo1.pdf"') == 'TDS-LabVIEW-2017-grupo1.pdf'
    assert p('filename="Soluciones_Problemas_Tema4.pdf"') == 'Soluciones_Problemas_Tema4.pdf'
    assert p('filename="Presentacion_TC_18-19.pdf"') == 'Presentacion_TC_18-19.pdf'
    assert p('filename="Actividad aula RFC.doc"') == 'Actividad aula RFC.doc'
    assert p('filename="Instrucciones de envio  P6.docx"') == 'Instrucciones de envio  P6.docx'
    assert p('filename="atm.pdf"') == 'atm.pdf'
    assert p('filename="seA+-ales grupo 1.zip"') == 'seA+-ales grupo 1.zip'
    assert p('filename="TDS_Teoria jun_1Aa_2017.pdf"') == 'TDS_Teoria jun_1Aa_2017.pdf'
    assert p('filename="ejercicio-5.6.pdf"') == 'ejercicio-5.6.pdf'
    assert p('filename="p4.pdf"') == 'p4.pdf'
    assert p('filename="TDS_Teoria jun_2Aa_2017.pdf"') == 'TDS_Teoria jun_2Aa_2017.pdf'
    assert p('filename="Frame Relay.pdf"') == 'Frame Relay.pdf'
    assert p('filename="Tablas_Tema1.pdf"') == 'Tablas_Tema1.pdf'
    assert p('filename="IniADDA2.vi"') == 'IniADDA2.vi'
    assert p('filename="WriteDA2.vi"') == 'WriteDA2.vi'
    assert p('filename="Soluciones_Problemas_Tema3.pdf"') == 'Soluciones_Problemas_Tema3.pdf'
    assert p('filename="x.25.pdf"') == 'x.25.pdf'
    assert p('filename="RFC.pdf"') == 'RFC.pdf'
    assert p('filename="EX_JUN_2018_UNI.pdf"') == 'EX_JUN_2018_UNI.pdf'
    assert p('filename="T-REC-I.620-199610-FRELAY.pdf"') == 'T-REC-I.620-199610-FRELAY.pdf'
    assert p('filename="Instrucciones de envio  P6.docx"') == 'Instrucciones de envio  P6.docx'
    assert p('filename="boll sa_FEB_2010.pdf"') == 'boll sa_FEB_2010.pdf'
    assert p('filename="iprt1314_examen_febrero.pdf"') == 'iprt1314_examen_febrero.pdf'
    assert p('filename="ATM.pdf"') == 'ATM.pdf'
    assert p('filename="ProblemasResueltos_Tema5.pdf"') == 'ProblemasResueltos_Tema5.pdf'
    assert p('filename="Tema3_Curso2018-2019.pdf"') == 'Tema3_Curso2018-2019.pdf'
    assert p('filename="MENTOR_2015.pdf"') == 'MENTOR_2015.pdf'
    assert p('filename="GRADO 01 concepto y divisiA3n.pdf"') == 'GRADO 01 concepto y divisiA3n.pdf'
    assert p('filename="grado. 02 el patrimonio.pdf"') == 'grado. 02 el patrimonio.pdf'
    assert p('filename="SSLATTACK (1)"') == 'SSLATTACK (1)'
    assert p('filename="iprt1819_tema5_notas.pdf"') == 'iprt1819_tema5_notas.pdf'
    assert p('filename="p2.pdf"') == 'p2.pdf'
    assert p('filename="CAP.CPTA._MOD_para_chicos2.pdf"') == 'CAP.CPTA._MOD_para_chicos2.pdf'
    assert p('filename="PRISA_ciclo contable.pdf"') == 'PRISA_ciclo contable.pdf'
    assert p('filename="iprt1819_notas_ordinaria.pdf"') == 'iprt1819_notas_ordinaria.pdf'
    assert p('filename="lomasa_2014_BC_campus virtual.pdf"') == 'lomasa_2014_BC_campus virtual.pdf'
    assert p('filename="captura.pcapng"') == 'captura.pcapng'
    assert p('filename="graficas.pcapng"') == 'graficas.pcapng'
    assert p('filename="P25.pcapng"') == 'P25.pcapng'
    assert p('filename="Pract4-tutorial_TimeQuest.pdf"') == 'Pract4-tutorial_TimeQuest.pdf'
    assert p('filename="PRISA_paraCHICOS.pdf"') == 'PRISA_paraCHICOS.pdf'
    assert p('filename="iprt1819_notas_informe3.pdf"') == 'iprt1819_notas_informe3.pdf'
    assert p('filename="T-REC-X.25-199610.pdf"') == 'T-REC-X.25-199610.pdf'
    assert p('filename="ARTACULO_OTN.pdf"') == 'ARTACULO_OTN.pdf'
    assert p('filename="Tema 4. El ciclo contable.pdf"') == 'Tema 4. El ciclo contable.pdf'
    assert p('filename="Calificaciones_P1.pdf"') == 'Calificaciones_P1.pdf'
    assert p('filename="MAX2_jul_2016_PPDF.pdf"') == 'MAX2_jul_2016_PPDF.pdf'
    assert p('filename="ejercicio-5.1.pdf"') == 'ejercicio-5.1.pdf'
    assert p('filename="2 de periodif.pdf"') == '2 de periodif.pdf'
    assert p('filename="Calificaciones_P2.pdf"') == 'Calificaciones_P2.pdf'
    assert p('filename="quA(c) PGC comprar.pdf"') == 'quA(c) PGC comprar.pdf'
    assert p('filename="HUECO1_julio2017.pdf"') == 'HUECO1_julio2017.pdf'
    assert p('filename="Plan de Trabajo_TDS_2019.pdf"') == 'Plan de Trabajo_TDS_2019.pdf'
    assert p('filename="T-REC-Y.1310-200003-ATM.pdf"') == 'T-REC-Y.1310-200003-ATM.pdf'
    assert p('filename="iprt1516_examen_ordinario.pdf"') == 'iprt1516_examen_ordinario.pdf'
    assert p('filename="iprt1819_notas_informe4.pdf"') == 'iprt1819_notas_informe4.pdf'
    assert p('filename="Instalacion de labview 2019.pdf"') == 'Instalacion de labview 2019.pdf'
    assert p('filename="Tema2.ppsx"') == 'Tema2.ppsx'
    assert p('filename="PasantAa (3).pdf"') == 'PasantAa (3).pdf'
    assert p('filename="iprt1819_notas_informe2.pdf"') == 'iprt1819_notas_informe2.pdf'
    assert p('filename="BS_PyG_modelo.pdf"') == 'BS_PyG_modelo.pdf'
    assert p('filename="iprt1819_notas_extraordinaria.pdf"') == 'iprt1819_notas_extraordinaria.pdf'
    assert p('filename="turnos_2_2019.pdf"') == 'turnos_2_2019.pdf'
    assert p('filename="Notas-TC-Enero-2019.pdf"') == 'Notas-TC-Enero-2019.pdf'
    assert p('filename="EJERCICIOS 3 PRIMEREOS TEMAS.pdf"') == 'EJERCICIOS 3 PRIMEREOS TEMAS.pdf'
    assert p('filename="p2_TDS_2019.pdf"') == 'p2_TDS_2019.pdf'
    assert p('filename="turnos_iniciales_2019.pdf"') == 'turnos_iniciales_2019.pdf'
    assert p('filename="tema5.pdf"') == 'tema5.pdf'
    assert p('filename="SCG_Tema_5_2015_16.pdf"') == 'SCG_Tema_5_2015_16.pdf'
    assert p('filename="IUT-T_Aula2019.pptx"') == 'IUT-T_Aula2019.pptx'
    assert p('filename="Ejemplo_lectura_grupo2.zip"') == 'Ejemplo_lectura_grupo2.zip'
    assert p('filename="Ejemplo_lectura_grupo1.zip"') == 'Ejemplo_lectura_grupo1.zip'
    assert p('filename="Tema2_Curso2018-2019.pdf"') == 'Tema2_Curso2018-2019.pdf'
    assert p('filename="Tema4_parte_1_SCG.pdf"') == 'Tema4_parte_1_SCG.pdf'
    assert p('filename="WAN2_2018-2019_TELEF.ppt"') == 'WAN2_2018-2019_TELEF.ppt'
    assert p('filename="Tema1_Curso2018-2019.pdf"') == 'Tema1_Curso2018-2019.pdf'
    assert p('filename="ARTACULO X25_FR_ATM.pdf"') == 'ARTACULO X25_FR_ATM.pdf'
    assert p('filename="Tema4_Curso2018-2019.pdf"') == 'Tema4_Curso2018-2019.pdf'
    assert p('filename="WAN1_2018-2019_CONMUTPKTS.ppt"') == 'WAN1_2018-2019_CONMUTPKTS.ppt'
    assert p('filename="SCG_Tema4_parte_2.pdf"') == 'SCG_Tema4_parte_2.pdf'
    assert p('filename="GRADO. 07 cuentas de personal.pdf"') == 'GRADO. 07 cuentas de personal.pdf'
    assert p('filename="atm.pptx"') == 'atm.pptx'
    assert p('filename="dispersion_avi.avi"') == 'dispersion_avi.avi'
    assert p('filename="Tema1.ppsx"') == 'Tema1.ppsx'
    assert p('filename="compensacion_FBG_avi.avi"') == 'compensacion_FBG_avi.avi'
    assert p('filename="wdm_avi.avi"') == 'wdm_avi.avi'
    assert p('filename="PacketTracer63_setup.exe"') == 'PacketTracer63_setup.exe'


def test_set_root_folder():
    root_folder = Options.ROOT_FOLDER
    temp_folder = 'temp-root-folder-to-delete'

    assert not os.path.isdir(temp_folder)
    Options.set_root_folder(temp_folder)
    assert os.path.isdir(temp_folder)

    Options.set_root_folder(root_folder)
    assert os.path.isdir(root_folder)

    os.rmdir(temp_folder)
    assert not os.path.isdir(temp_folder)


# noinspection PyTypeChecker
def test_set_timeout():
    Options.set_timeout(1)
    assert Options.TIMEOUT == 1

    Options.set_timeout(2)
    assert Options.TIMEOUT == 2

    with pytest.raises(TypeError, 'Timeout must be int, not'):
        Options.set_timeout('3')
    with pytest.raises(TypeError, 'Timeout must be int, not'):
        Options.set_timeout(False)
    with pytest.raises(TypeError, 'Timeout must be int, not'):
        Options.set_timeout(None)
    with pytest.raises(TypeError, 'Timeout must be int, not'):
        Options.set_timeout(1 + 2j)
    with pytest.raises(TypeError, 'Timeout must be int, not'):
        Options.set_timeout(7.22)
    with pytest.raises(TypeError, 'Timeout must be int, not'):
        Options.set_timeout([3, 2])
    with pytest.raises(TypeError, 'Timeout must be int, not'):
        Options.set_timeout((2, 3))

    Options.set_timeout(30)

# todo test Options.load_config
